# Generated by Django 4.2.7 on 2023-11-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_manager', '0005_invite_rename_serveradmin_servermanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('threshold', models.FloatField()),
                ('condition', models.CharField(choices=[('greater_than', 'Greater Than'), ('less_than', 'Less Than')], max_length=20)),
                ('action', models.CharField(choices=[('send_email', 'Send Email'), ('send_sms', 'Send SMS')], max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.server')),
            ],
        ),
    ]
