# Generated by Django 4.2.7 on 2023-11-10 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_manager', '0002_server_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='user',
        ),
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(related_name='admin_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
