# Generated by Django 4.2.7 on 2023-11-10 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_manager', '0004_remove_server_admins_server_user_serveradmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.server')),
            ],
        ),
        migrations.RenameModel(
            old_name='ServerAdmin',
            new_name='ServerManager',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
    ]
